# Generated by Django 5.0.14 on 2026-03-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationreport',
            name='number_plate',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
